import { useState, useEffect, Suspense } from 'react'
import dynamic from "next/dynamic";
import Head from 'next/head'
import Header from '@/components/header'
import styles from '@/styles/Artist.module.scss'
import { fetchContent } from '@/api/strapi'
import { markdownDesc } from '@/constants/helpers'

export const Artists = ({ artists = {} }) => {
  const Artists = dynamic(() => import('@/components/artists'), {
    suspense: true,
  })

  return (
    <>
      <Head>
        <title>Shinobi Tattoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header standalone />
      <main className={styles.container}>
        {
          !!artists.length ?
            <div className={styles.area}>
              <div className={styles.content}>
                <Suspense fallback={<div>...</div>}>
                  <Artists data={artists} standalone />
                </Suspense>
              </div>
            </div> : <></>
        }
      </main>
    </>
  )
}

export async function getServerSideProps({ params }) {
  const artists = await fetchContent(`artists`)

  return {
    props: {
      artists,
    }
  }
}


export default Artists