import Head from 'next/head'
import Header from '@/components/header'
import styles from '@/styles/Artist.module.scss'
import { fetchContent } from '@/api/strapi'

export const About = ({ gallery }) => {

  return (
    <>
      <Head>
        <title>Shinobi Tattoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header standalone />
      <main className={styles.container}>
        <h1><span>About</span></h1>
      </main>
    </>
  )
}

export async function getServerSideProps({ params }) {
  const gallery = await fetchContent(`gallery`)

  return {
    props: {
      gallery,
    }
  }
}

export default About