import Head from 'next/head'
import Markdown from 'react-markdown'
import Header from '@/components/header'
import styles from '@/styles/Artist.module.scss'
import { fetchContent } from '@/api/strapi'
export const About = ({ about }) => {

  console.log('about:', about)
  return (
    <>
      <Head>
        <title>Shinobi Tattoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header standalone />
      <main className={styles.container}>
        <h1><span>About</span></h1>
        <Markdown>
          {about.description}
        </Markdown>
      </main>
    </>
  )
}

export async function getServerSideProps({ params }) {
  const about = await fetchContent(`about`)

  return {
    props: {
      about,
    }
  }
}

export default About