import { useRef, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Header from '@/components/header'
import styles from '@/styles/ContactPage.module.scss'
import Icons from '@/components/icons'

export const Contact = ({}) => {
    const [active, setActive] = useState(0)
    const [showSuccess, setShowSuccess] = useState(false)
    const [loading, setLoading] = useState(false)
    const nameRef = useRef()
    const phoneRef = useRef()
    const textRef = useRef()
    const sendMail = () => {
      setLoading(true)

    const data = {
      name: nameRef.current.value,
      phone: phoneRef.current.value,
      text: textRef.current.value,
    }

    const required = [
      nameRef,
      phoneRef,
      textRef,
    ]

    if (required.every(val => !!val.current.value)) {
      required.forEach(ref => {
        ref.current.classList.remove(styles.error)
      })
      const apiEndpoint = '/api/email';

      fetch(apiEndpoint, {
        method: 'POST',
        body: JSON.stringify(data),
      })
        .then((res) => res.json())
        .then((response) => {
          console.log('response', response)
          setShowSuccess(true)
          setLoading(false)
          reset()
        })
        .catch((err) => {
          setLoading(false)
          alert(err);
        });
    } else {
      required.forEach(ref => {
        if (!ref.current.value) {
          ref.current.classList.add(styles.error)
        } else {
          ref.current.classList.remove(styles.error)
        }
      });
    }
  }

  const reset = () => {
    nameRef.current.value = ''
    phoneRef.current.value = ''
    textRef.current.value = ''
  }

  return (
    <>
      <Head>
        <title>Shinobi Tattoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header standalone />
      <main className={styles.container}>
        <h1><span>Kontakt</span></h1>
        <div className={styles.contactWrapper}>
        <div className={styles.contactLeft}>
        <div className={styles.accordionElement}>

          <div className={styles.accordionTitle} onClick={() => setActive(active === 1 ? 0 : 1)}>
            <h4>
                Wie kriege ich einen Termin?
            </h4>
            <Icons name={active === 1 ? 'expand' : 'forth'} size={20} />
          </div>
          <div className={`${styles.accordionContent} ${active === 1 ? styles.elementOpen : ''}`}>
            Schreibe uns über das Kontaktformular oder direkt über unsere Social Media Accounts.
            Deine Nachricht sollte folgende Infos enthalten:
            <ul>
                <li>Name, Alter (min 18*)</li>
                <li>Kurze Beschreibung deiner Idee</li>
                <li>Wenn du Referenzbilder hast, kannst du diese beilegen</li>
                <li>Wo du das Tattoo gerne möchtest und eine ungefähre Frössenangabe</li>
                <li>Was ist dein Budget</li>
                <li>Wann hast du Zeit für eine Besprechung (DI - SA)</li>
            </ul>
          </div>
        </div>
        <div className={styles.accordionElement}>
          <div className={styles.accordionTitle} onClick={() => setActive(active === 2 ? 0 : 2)}>
            <h4>
                Was muss ich beachten?
            </h4>
            <Icons name={active === 2 ? 'expand' : 'forth'} size={20} />
          </div>
          <div className={`${styles.accordionContent} ${active === 2 ? styles.elementOpen : ''}`}>
            Vor dem Termin:
            <ul>
                <li>Bitte sei pünktlich vor Ort</li>
                <li>Am Vorabend kein übermässiger Alkohol- oder Drogenkonsum</li>
                <li>2 Wochen keine Blutverdünner einnehmen</li>
                <li>Dein allgemeiner Gesundheitszustand sollte am Termin gut sein</li>
                <li>Iss vor dem Termin etwas und nimm ein Süssgetränk mit</li>
                <li>Plane keine Badeferien direkt nach dem Termin!</li>
                <li>Achtung - mit Sonnenbrand kann ich dich nicht tätowieren</li>
                <li>Du musst die Stelle nicht selber rasieren</li>
                <li>Duschen macht Spass ;)</li>
            </ul>
          </div>
        </div>
        <div className={styles.accordionElement}>
          <div className={styles.accordionTitle} onClick={() => setActive(active === 3 ? 0 : 3)}>
            <h4>
                Pflegehinweise
            </h4>
            <Icons name={active === 3 ? 'expand' : 'forth'} size={20} />
          </div>
          <div className={`${styles.accordionContent} ${active === 3 ? styles.elementOpen : ''}`}>
            <a href='/Pflegeanleitung.jpg' target='_blank' rel='noreferrer noopener'>
                <Image src={'/Pflegeanleitung.jpg'}
                    width={400}
                    height={200}
                />
            </a>
          </div>
        </div>
        </div>
        <div className={styles.verticalSplit}></div>
        <div className={styles.contactRight}>
          <label>
            Name *
            <input type="text" ref={nameRef} disabled={loading} />
          </label>
          <label>
            Telefon *
            <input type="tel" ref={phoneRef} disabled={loading} />
          </label>
          <label>
            Nachricht *
            <textarea ref={textRef} disabled={loading}></textarea>
          </label>
          <button disabled={loading} onClick={sendMail}>Senden</button>
            {
              showSuccess &&
                <div className={styles.success} uk-alert>
                  <div>
                    Deine Anfrage wurde erfolgreich abgeschickt. Wir melden uns bei dir!
                  </div>
                  <Icons name="close" size="35" clickAction={() => setShowSuccess(false)}/>
                </div>
            }
        </div>
      </div>
      </main>
    </>
  )
}

export default Contact