import { useState } from 'react'
import Head from 'next/head'
import Header from '@/components/header'
import styles from '@/styles/Gallery.module.scss'
import { fetchContent } from '@/api/strapi'
import { useSwiper, Swiper, SwiperSlide } from 'swiper/react'

// Import Swiper styles
import 'swiper/css';
import 'swiper/css/navigation';


// import required modules
import { FreeMode, Navigation, Thumbs } from 'swiper/modules';
import Icons from '@/components/icons'


export const Gallery = ({ gallery }) => {
    const [isOpen, setIsOpen] = useState(false);
    const [activeIndex, setActiveIndex] = useState(0);

    const openGallery = (index) => {
        document.getElementsByTagName('body')[0].style.overflow = 'hidden'
        setActiveIndex(index)
        setIsOpen(true)
    }
    const closeGallery = () => {
        document.getElementsByTagName('body')[0].style.overflow = ''
        setIsOpen(false)
    }

    const swiperLoad = (swiper) => {
        swiper.slideTo(activeIndex);
    }

  return (
    <>
      <Head>
        <title>Shinobi Tattoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header standalone />
      <main className={styles.container}>
        <h1><span>Gallery</span></h1>
        <div className={styles.galleryWrapper}>
            {
                gallery.images?.map((image, index) =>
                    <div className={styles.imageWrapper} key={image.formats.medium.name}>
                        <div
                            style={{ backgroundImage: `url(${image.formats.medium.url})` }}
                            alt={image.formats.medium.name}
                            className={styles.image}
                            onClick={() => openGallery(index)}
                        >
                        </div>
                    </div>
                )
            }
        </div>
        {
            isOpen &&
                <div className={styles.carouselWrapper}>
                    <div className={styles.carouselContainer}>
                        <div className={styles.close} onClick={closeGallery}>
                            <Icons name='close' size='36' />
                        </div>
                        <Swiper
                            loop={true}
                            spaceBetween={10}
                            navigation
                            modules={[FreeMode, Navigation]}
                            className={styles.mySwiperWrapper}
                            style={{
                                '--swiper-theme-color': '#fff',
                                '--swiper-navigation-size': '24px',
                            }}
                            onSwiper={swiperLoad}
                        >
                            {gallery.images?.map(image => (
                                <SwiperSlide className={styles.slide} key={image.formats.large.name}>
                                    <img src={`${image.formats.large.url}`} />
                                </SwiperSlide>
                            ))}
                        </Swiper>
                    </div>
                </div>
        }
      </main>
    </>
  )
}

export async function getServerSideProps({ params }) {
  const gallery = await fetchContent(`galleries`)

  return {
    props: {
      gallery: gallery[0] || {},
    }
  }
}

export default Gallery