import Head from 'next/head'
import Script from 'next/script'
import { fetchContent } from '../src/api/strapi'
import Header from '@/components/header'
import Welcome from '@/components/home'
import News from '@/components/news'
import Artists from '@/components/artists'
import Gallery from '@/components/gallery'
import Contact from '@/components/contact'
import styles from '@/styles/Home.module.scss'

export default function Home({ home, articles, artists, gallery }) {
  const scrollDown = () => {
    window.scrollTo({top: window.innerHeight, behavior: 'smooth'});
  }

  return (
    <>
      <Script src="https://cdn.jsdelivr.net/npm/uikit@3.15.12/dist/js/uikit.min.js"></Script>
      <Script src="https://cdn.jsdelivr.net/npm/uikit@3.15.12/dist/js/uikit-icons.min.js"></Script>
      <Head>
        <title>Shinobi Tattoo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.15.12/dist/css/uikit.min.css" />
      </Head>
      <main className={styles.main}>
        <div uk-parallax="bgy: -100" className={styles.top}>
          <div className={styles.logo}>
            <img src="https://shinobi-aws-s3-images-bucket.s3.eu-central-1.amazonaws.com/medium_shinobi_logo_ce066ca1ac.png" />
          </div>
          <div className={styles.scrolldownWrapper}>
            <div className={styles.mouse} onClick={scrollDown}></div>
          </div>
        </div>
        <div className={styles.area}>
          <div className={styles.content}>
            <Welcome data={home.attributes.home[0]} />
          </div>
        </div>
        <div className={styles.divider}></div>
        <div className={styles.area}>
          <div className={styles.content}>
            <News data={articles} />
          </div>
        </div>
        <div className={styles.area}>
          <div className={styles.content}>
            <Artists data={artists} />
          </div>
        </div>
        <div className={styles.area}>
          <div className={styles.content}>
            <Gallery data={gallery} />
          </div>
        </div>
        <div className={styles.area}>
          <div className={styles.content}>
            <Contact />
          </div>
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  const home = await fetchContent('homepage')
  const articles = await fetchContent('articles')
  const artists = await fetchContent('artists')
  const gallery = await fetchContent('galleries')

  return {
    props: {
      home,
      articles,
      artists,
      gallery,
    }
  }
}
